Think about storing data into array of numbers. Any information(sound, text, pictures) can be converted into arrays of numbers.

Numpy forms the basis of almost all data science packages and libraries used in Python

In [1]:
import numpy as np

Python is a dynamically typed language, and therefore one result is that the data types do not need to be explicitly declared.

However, due to this, Python variables dont only contain the data that is stored in them, but they also contain information on the type of data that is stored in them. 

The standard Python implementation is all written in C. 

A simple integer object in Python contains the following pieces of information:

* ob_refcnt, which is a reference count that allows Python to handle memory allocation and deallocation
* ob_type , which contains information on the type of variable
* ob_size, which specifies the size of the data members
* ob_digit, which contains the actual values of the data stored in the integer object. 

When we start storing several of such Python objects in a list, we need to be aware about the additional information(apart from just the data values) that Python objects contain. 

Lets create a list of integers

In [3]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
type(L[0])

int

Lets now create a list of strings. 

In [6]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [7]:
type(L2[0])

str

Lets creae a hetrogenous string.

In [8]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In cases where all elements in the array are of the same type, it makes more sense to store them in a fixed-type array. 

The in-built **array** library can be used for creating fixed-style arrays. 

In [10]:
import array

In [11]:
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

A better way of creating fixed-type arrays is my using the **ndarray** object in the Numpy package. 

In [13]:
#create an integer list
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

We can use in-built numpy functions to create different fixed-type arrays. 

In [14]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [17]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.76681579, 0.83294118, 0.92725127],
       [0.66720985, 0.1803045 , 0.68077776],
       [0.49560768, 0.24807219, 0.76646232]])

In [20]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.16622997,  0.35677096,  0.94955271],
       [-0.52802071,  2.5360677 ,  0.04253529],
       [-0.56368989,  0.34999986,  0.76947148]])

In [21]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[7, 5, 7],
       [6, 3, 0],
       [7, 5, 5]])

In [22]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])